language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install
script:
- cd tests
- python -m unittest
deploy:
  provider: heroku
  api_key: e0161902-f473-41b4-8653-99af53ff59a1
  app: ortosia-telegram-bot
  on:
    all_branches: true
  skip_cleanup: true
# branches:
#   only:
#   - master
