language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install
script:
- cd tests
- python -m unittest
deploy:
  provider: script
  script: 
    heroku git:remote -a ortosia-telegram-bot
    git push heroku master
  on:
    all_branches: true
  skip_cleanup: true
# branches:
#   only:
#   - master
