language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install
script:
- cd tests
- python -m unittest
deploy:
  provider: heroku
  api_key:
    secure: rZlMNpc8eFGQ3fDU1AuHKaejtG5TXKVeu4gdRgFN4FqJshGWrKncDgedXFT0CdWp39xGigo5ByF8zbMg2Gn/vF9kauuhZdMX3sHb3ymlKFrWUvRYCcymDm/YCbeDSO2hawEFe8+KDMg0MtwiQaNpoEYJxvUUbDHE4NJKSi3Q1bS7r8oSoz4kZWK47+0D6Ck6M6A79lRgDoa5YPTkx4QksYweQ5V67OV/7I1uVSehRgtI/JQKDoTy+6XWN7SGoGDTcR314NTrEoR37b6iBIH59gnyPzEyIcz/6FLxzlxfB5AJ/hrnfBd3ioqqARqlBjmQ+MECvKtQRldIOpifQCQABDdRp+8Nw1jEtHzLAQ6hbzdCtsuykpbQ1E8seruEiSc8qsK6YQqq4KR0mbW5T8/e+YdRW77G82bE2kcyiXkalQRN1HRPVBsmj5gJ5Lh5AeHPQeebdtvjjtK9HXW9ZPdo36zYEJ9p1DBj/C3CV44Vf28eITG31EMfnAjNcJWgF6N93PbSq4tJse7e4yU8hko4jnEqNo5WHYaVrTbMvLlj6Wviexf3cfHitnl9lBh7/iYCT+TXi7arKD6mpbllA214WBtnRW3vyE7xHYXlgXr6oVQRFXtfHN0AJZ+I3nhbWzjliZS9HKTSe2V6zmPUw9Z6hFGekr6Hph0xabiFIQMZEPw=
branches:
  only:
  - master
